DjangoWebProject2/DjangoWebProject2/urls.py
"""
Definition of urls for DjangoWebProject2.
"""

from datetime import datetime
from django.urls import path
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from app import forms, views

from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings

urlpatterns = [
    path('', views.home, name='home'),
    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name='about'),
    path('links/', views.links, name = 'links'),
    path('anketa/', views.anketa, name = 'anketa'),
    path('blog/', views.blog, name = 'blog'),
    path('blogpost/<int:parametr>/', views.blogpost, name='blogpost'),
    path('newpost/', views.newpost, name='newpost'),
    path('videopost/', views.videopost, name='videopost'),
    path('login/',
         LoginView.as_view
         (
             template_name='app/login.html',
             authentication_form=forms.BootstrapAuthenticationForm,
             extra_context=
             {
                 'title': 'Авторизация',
                 'year' : datetime.now().year,
             }
         ),
         name='login'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('admin/', admin.site.urls),
    path('registration/', views.registration, name = 'registration'),
]
urlpatterns += static( settings.MEDIA_URL, document_root = settings.MEDIA_ROOT )
urlpatterns += staticfiles_urlpatterns()

DjangoWebProject2/app/forms.py
"""
Definition of forms.
"""

from unittest.util import _MAX_LENGTH
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.utils.translation import gettext_lazy as _
from django.db import models
from .models import Comment
from .models import Blog


class BootstrapAuthenticationForm(AuthenticationForm):
    """Authentication form which uses boostrap CSS."""
    username = forms.CharField(max_length=254,
                               widget=forms.TextInput({
                                   'class': 'form-control',
                                   'placeholder': 'Логин'}))
    password = forms.CharField(label=_("Password"),
                               widget=forms.PasswordInput({
                                   'class': 'form-control',
                                   'placeholder':'Пароль'}))

class AnketaForm(forms.Form):
    name = forms.CharField(label='Ваше имя', min_length=2, max_length=100)
    city = forms.CharField(label='Ваш город', min_length=2, max_length=100)
    job = forms.CharField(label='Ваш род занятий', min_length=2, max_length=100)
    gender = forms.ChoiceField(label='Ваш пол',
        choices=[('1', 'Мужской'), ('2', 'Женский')],
        widget=forms.RadioSelect, initial=1)
    like = forms.ChoiceField(label='Вам нравится наш сайт?',
        choices=[('1', 'Очень'),
                ('2', 'Не очень'),
                ('3', 'Очень'),
                ('4', 'Не очень')], initial=1)
    notice = forms.BooleanField(label='Получать новости сайта на e-mail?',
        required=False)
    email = forms.EmailField(label='Ваш e-mail', min_length=7)
    message = forms.CharField(label='Коротко о себе',
        widget=forms.Textarea(attrs={'rows':12,'cols':20}))

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment    # используемая модель
        fields = {'text',}    # требуется заполнить только поле text
        labels = {'text': "Комментарий"}    # метка к полю формы text

class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ('title', 'description', 'content', 'image',)
        labels = {'title':'Заголовок', 'description':'Краткое содержание', 'content':'Полное содержание', 'image':'Картинка'}

DjangoWebProject2/app/templates/app/about.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>

<p>Use this area to provide additional information.</p>

{% endblock %}

DjangoWebProject2/app/templates/app/anketa.html
{% extends "app/layout.html" %}
{% load static %}
{% block content %}
{% if form != None %}
<br>
<h2>Отправьте пожалуйста заполненную анкету</h2>
<br>
<div>
    <form method="post" >
        {% csrf_token %}
        <label for="{{ form.name.id_for_label }}">{{ form.name.label }}:</label>
        {{ form.name }}<br><br>

        <label for="{{ form.city.id_for_label }}">{{ form.city.label }}:</label>
        {{ form.city }}<br>

        <label for="{{ form.gender.id_for_label }}">{{ form.gender.label }}:</label>
        {{ form.gender }}

        <label for="{{ form.job.id_for_label }}">{{ form.job.label }}:</label><br>
        {{ form.job }}<br><br>

        <label for="{{ form.like.id_for_label }}">{{ form.like.label }}:</label><br>
        {{ form.like }}<br><br>

        <label for="{{ form.notice.id_for_label }}">{{ form.notice.label }}:</label>
        {{ form.notice }}<br><br>

        <label for="{{ form.email.id_for_label }}">{{ form.email.label }}:</label>
        {{ form.email }}<br><br>

        <label for="{{ form.message.id_for_label }}">{{ form.message.label }}:</label><br>
        {{ form.message }}<br><br>

        <input type="submit" value="Отправить" id="Submit">
    </form>
</div>
{% else %}
<br>
<h2>Благодарим за предоставленную информацию!</h2>
<h3>Вы сообщили о себе следующее:</h3>
<ul>
    <li><span>Имя: </span>{{ data.name }}</li>
    <li><span>Город: </span>{{ data.city }}</li>
    <li><span>Пол: </span>{{ data.gender }}</li>
    <li><span>Работа: </span>{{ data.job }}</li>
    <li><span>Симпатия: </span>{{ data.like }}</li>
    <li><span>Получать новости сайта на e-mail: </span>{{ data.notice }}</li>
    <li><span>Ваш e-mail: </span>{{ data.email }}</li>
    <li><span>Информация о себе: </span>{{ data.message }}</li>
</ul>
{% endif %}
{% endblock %}
{% block scripts %}
<script src="{% static 'app/scripts/jquery-1.10.2.js' %}"></script>
<script>

    function Submit_over() {

        $('#Submit').css('color', 'pink');

    }
    function Submit_out() {
        $('#Submit').css('color', 'black');
    }
    function name_focus() {
        $('#id_name').css('background-color', 'pink');
    }
    function name_blur() {
        $('#id_name').css('background-color', 'white');
    }
    function city_focus() {
        $('#id_city').css('background-color', 'pink');
    }
    function city_blur() {
        $('#id_city').css('background-color', 'white');
    }
    function job_focus() {
        $('#id_job').css('background-color', 'pink');
    }
    function job_blur() {
        $('#id_job').css('background-color', 'white');
    }
    function email_focus() {
        $('#id_email').css('background-color', 'pink');
    }
    function email_blur() {
        $('#id_email').css('background-color', 'white');
    }
    function message_focus() {
        $('#id_message').css('background-color', 'pink');
    }
    function message_blur() {
        $('#id_message').css('background-color', 'white');
    }
    $('#Submit').mouseover(Submit_over);
    $('#Submit').mouseout(Submit_out);
    $('#id_name').focus(name_focus);
    $('#id_name').blur(name_blur);
    $('#id_city').focus(city_focus);
    $('#id_city').blur(city_blur);
    $('#id_job').focus(job_focus);
    $('#id_job').blur(job_blur);
    $('#id_email').focus(email_focus);
    $('#id_email').blur(email_blur);
    $('#id_message').focus(message_focus);
    $('#id_message').blur(message_blur);
</script>
{% endblock %}

DjangoWebProject2/app/templates/app/blog.html
{% extends "app/layout.html" %}
{% block content %}
<h2>{{ title }}</h2>
<br />
{% for post in posts %}
<hr />
<div class="">
    <h2> {{post.title}} </h2>
    <h4> {{post.posted}} </h4>
    <p> {{post.description}} </p>
    <p><a href="{% url 'blogpost' parametr=post.id %}"> Читать далее </a> </p>
</div>
{% endfor %}
{% endblock %}

DjangoWebProject2/app/templates/app/blogpost.html
{% extends "app/layout.html" %}
{% block content %}
<h2> {{post_1.title}} </h2>
{% if post_1.image and post_1.image.url != '/media/temp.jpg' %}
<img src="{{ post_1.image.url }}" alt="Картинка статьи блога" width="200" />
{% endif %}
<p> {{post_1.content|linebreaksbr}} </p>      {# вывод текста по абзацам#}

{% if user.is_authenticated %}
<h3>Добавить комментарий</h3>
<form method="POST">
    {% csrf_token %}    {# защита от атак CSRF #}
    <div>
        {{form.as_p}}
        <button type="submit" class="save btn btn-default"> Отправить комментарий </button>
    </div>
</form>
{% else %}
<h3> Для добавления своего комментария, пожалуйста, авторизуйтесь </h3>
{% endif %}
<br />
<br />

{% for comment in comments %}
<hr />
<h7> {{comment.date}} </h7>
<h5> {{comment.author}} </h5>
<p> {{comment.text|linebreaksbr}} </p>
{% endfor %}

<p><a href="{% url 'blog' %}">Назад</a></p>
{% endblock %}

DjangoWebProject2/app/templates/app/contact.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>

<address>
    Улица Пушкина<br />
    Дом Колотушкина<br />
    <abbr title="Телефон">Тел:</abbr>
    88005553535
</address>

<address>
    <strong>Поддержка:</strong>   <a href="https://www.youtube.com/watch?v=dQw4w9WgXcQ" target="_blank">Её нет!""</a><br />

</address>

{% endblock %}

DjangoWebProject2/app/templates/app/index.html
{% extends "app/layout.html" %}
{% block content %}
{% load static %}

<!--<div class="jumbotron">
    <h1>Django</h1>
    <p class="lead">Django is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://www.djangoproject.com/" class="btn btn-primary btn-large">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            Django gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://djangobook.com/django-tutorials/">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>The Python Package Index is a repository of software for the Python programming language.</p>
        <p><a class="btn btn-default" href="https://pypi.org/">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Microsoft Azure</h2>
        <p>You can easily publish to Microsoft Azure using Visual Studio. Find out how you can host your application using a free trial today.</p>
        <p><a class="btn btn-default" href="http://azure.microsoft.com">Learn more &raquo;</a></p>
    </div>
</div>-->
<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="2000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="{% static 'app/content/chuvash1.jpg'%} " alt="Первый слайд" class="img-responsive" />
        </div>
        <div class="item">
            <img src="{% static 'app/content/chuvash2.jpg'%}" alt="Второй слайд" class="img-responsive" />
        </div>
        <div class="item">
            <img src=" {% static 'app/content/chuvash3.jpg'%} " alt="Третий слайд" class="img-responsive" />
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Назад</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Дальше</span>
    </a>
</div>

{% endblock %}

DjangoWebProject2/app/templates/app/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }} - My Django Application</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/bootstrap.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/site.css' %}" />
    <script src="{% static 'app/scripts/modernizr-2.6.2.js' %}"></script>
</head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/" class="navbar-brand"> <img src="{% static 'app/content/chuvash.png' %}" alt="logo" /> </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'home' %}">Домашняя страница</a></li>
                    <li><a href="{% url 'about' %}">О нас</a></li>
                    <li><a href="{% url 'contact' %}">Наши контакты</a></li>
                    <li><a href="{% url 'blog' %}">Блог</a></li>
                    <li><a href="{% url 'links' %}">Полезные ссылки</a></li>
                    <li><a href="{% url 'anketa' %}">Обратная связь</a></li>
                    {% if user.is_superuser %}
                    <li><a href="{% url 'newpost' %}">Добавить статью</a></li>
                    {% endif %}
                    <li><a href="{% url 'videopost' %}">Видео</a></li>
                    {% if not user.is_authenticated %}
                    <li><a href="{% url 'registration' %}">Регистрация</a></li>
                    {% endif %}
                </ul>
                {% include 'app/loginpartial.html' %}
            </div>
        </div>
    </div>

    <div class="container body-content">
{% block content %}{% endblock %}
        <hr/>
        <footer>
            <p>&copy; {{ year }} - My Django Application</p>
        </footer>
    </div>

    <script src="{% static 'app/scripts/jquery-1.10.2.js' %}"></script>
    <script src="{% static 'app/scripts/bootstrap.js' %}"></script>
    <script src="{% static 'app/scripts/respond.js' %}"></script>
{% block scripts %}{% endblock %}

</body>
</html>

DjangoWebProject2/app/templates/app/links.html
{% extends "app/layout.html" %}

{% block content %}
{% load static %}
<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>

<a href="https://www.youtube.com/watch?v=dQw4w9WgXcQ" target="_blank"> <img src="{% static 'app/content/youtube.png' %}" alt="Logo 1"  width="100" height="100"/></a>
<a href="https://www.youtube.com/watch?v=dQw4w9WgXcQ" target="_blank"> <img src="{% static 'app/content/youtube.png' %}" alt="Logo 1"  width="100" height="100"/></a>
<a href="https://www.youtube.com/watch?v=dQw4w9WgXcQ" target="_blank"> <img src="{% static 'app/content/youtube.png' %}" alt="Logo 1"  width="100" height="100"/></a>

{% endblock %}

DjangoWebProject2/app/templates/app/login.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}</h2>
<br />
<div class="row">
    <div class="col-md-8">
        <section id="loginForm">
            <form action="." method="post" class="form-horizontal">
                {% csrf_token %}
                <h4>Для входа в систему используйте локальную учетную запись.</h4>
                <hr />
                <div class="form-group">
                    <label for="id_username" class="col-md-2 control-label">Логин</label>
                    <div class="col-md-10">
                        {{ form.username }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="id_password" class="col-md-2 control-label">Пароль</label>
                    <div class="col-md-10">
                        {{ form.password }}
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="hidden" name="next" value="/" />
                        <input type="submit" value="Войти" class="btn btn-default" />
                    </div>
                </div>
                {% if form.errors %}
                <p class="validation-summary-errors">Пожалуйста, введите правильное имя пользователя и пароль.</p>
                {% endif %}
            </form>
        </section>
    </div>
    <div class="col-md-4">
        <section id="socialLoginForm"></section>
    </div>
</div>

{% endblock %}


{% block scripts %}

    {% load static %}
<script src="{% static 'app/scripts/jquery.validate.min.js' %}"></script>

{% endblock %}

DjangoWebProject2/app/templates/app/loginpartial.html
{% if user.is_authenticated %}
<form id="logoutForm" action="/logout/" method="post" class="navbar-right">
    {% csrf_token %}
    <ul class="nav navbar-nav navbar-right">
        <li><span class="navbar-brand">Hello {{ user.username }}!</span></li>
        <li><a href="javascript:document.getElementById('logoutForm').submit()">Выйти из аккаунта</a></li>
    </ul>
</form>

{% else %}

<ul class="nav navbar-nav navbar-right">
    <li><a href="{% url 'login' %}">Авторизация</a></li>
</ul>

{% endif %}

DjangoWebProject2/app/templates/app/newpost.html
{% extends "app/layout.html" %}

{% block content %}

<h3>Добавить статью</h3>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %} {# обязательная защита от атак CSRF #}
    <div>
        {{ blogform.as_p }}
        <button type="submit" class="save btn btn-default"> Сохранить статью </button>
    </div>
</form>

{% endblock %}

DjangoWebProject2/app/templates/app/registration.html
{% extends "app/layout.html" %}
{% block content %}

<h2>Регистрация пользователя</h2>
<form method="POST">

    {% csrf_token %}
    <div>
        {{ regform.as_p}}
        <button type="submit" class="save btn btn-default"> Зарегистрировать </button>
    </div>

</form>

{% endblock %}

DjangoWebProject2/app/templates/app/videopost.html
{% extends "app/layout.html" %}
{% block content %}
<h1>{{ title }}.</h1>
<hr />
<div>
    <h2>Видео 1</h2>
    <video src="/media/vidos1.mp4" controls="controls" width="400" height="300" poster="/media/cf8dbe5ae9652c18d4161acaedbfb652_e1ekbUu.jpg"></video>
</div>
<hr />
<div>
    <h2>Видео 2</h2>
    <video src="/media/vidos2.mp4" controls="controls" width="400" height="300" poster="/media/cf8dbe5ae9652c18d4161acaedbfb652_e1ekbUu.jpg"></video>
</div>
{% endblock %}